# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a34c5688c1721ff2338acf3864504f369654bb90edc52ce0c929851281229540242d9812f2fda9f269ad90cde9ea08a43fb6534acf35ce52638462cabbfd84

test:
  secret_key_base: ad8e13d74cac59ca1c7884cdd12d95f3ccd81b32d371c18518509e76106e63dfd1f8d47524be96dee98f78c891880488062b4db712c420f3e631b1cfc3102e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
